kind = "web"
previewPath = "/"
title = "Gym Manager"
version = "1.0.0"
id = "artifacts/gym-manager"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24266

[services.development]
run = "pnpm --filter @workspace/gym-manager run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/gym-manager", "run", "build" ]
serve = "static"
publicDir = "artifacts/gym-manager/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24266"
BASE_PATH = "/"
